production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: pull-requests
  pool: 5
  username:
  password:

development:
  adapter: postgresql
  database: pull_requests
  host: localhost
  encoding: unicode
  pool: 5
  username:
  password:
